language: java

jdk:
#  - oraclejdk8
  - oraclejdk7
#  - openjdk6

install: mvn clean install -Pprep-coverage -DskipTests=true -Dmaven.javadoc.skip=true -B -V

after_success:
  - mvn jacoco:report coveralls:report
